name: .NET Core Build and Run Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies for project
      run: dotnet restore ~/work/SmartExtensions/SmartExtensions/SmartExtensions/
    - name: Build
      run: dotnet build ./work/SmartExtensions/SmartExtensions/SmartExtensions/ --configuration Release --no-restore
    - name: Install dependencies for test project
      run: dotnet restore ~/work/SmartExtensions/SmartExtensions/SmartExtensions.Test/SmartExtensions.Test.csproj
    - name: Test
      run: dotnet test ~./SmartExtensions/SmartExtensions/SmartExtensions.Test/SmartExtensions.Test.csproj --no-restore --verbosity normal
