name: .NET Core Build and Run Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET 
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies for project
      run: dotnet restore ~/work/SmartExtensions/SmartExtensions/SmartExtensions/
    - name: Build
      run: dotnet build ~/work/SmartExtensions/SmartExtensions/SmartExtensions/SmartExtensions.csproj --configuration Release --no-restore
    - name: Install dependencies for test project
      run: dotnet restore ~/work/SmartExtensions/SmartExtensions/SmartExtensions.Test/
    - name: Test
      run: dotnet test ~/work/SmartExtensions/SmartExtensions/SmartExtensions.Test/SmartExtensions.Test.csproj --no-restore --verbosity normal
