name: Generate and Publish Nuget

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/DevsAnon/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        

      - name: Build solution and generate NuGet package
        run: |  
          cd ~/work/SmartExtensions/SmartExtensions/SmartExtensions/
          dotnet build -c release
      - name: Push generated package to GitHub registry
        run: dotnet nuget push ~/work/SmartExtensions/SmartExtensions/SmartExtensions/out/*.nupkg --skip-duplicate --no-symbols
